### ISSUE TITLE
compile proble

### ISSUE THREAD

**Issue by xiaoqiang-ok** [mozilla/LPCNet#47]
i work on a centos 7.2  linux system
when I do make， I encouter problem like：
src/vec.h:141:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'y'
          float * restrict y;
restrict need complile parameter：-std=c99

mysolution is：
export CFLAGS='-O3 -g -mavx2 -mfma **-std=c99**'
./configure
make
